set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 10.000 -name clk -waveform {0.000 5.000} -add [get_ports clk]

set_property PACKAGE_PIN C12 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_property PACKAGE_PIN J15 [get_ports {swt[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swt[0]}]
set_property PACKAGE_PIN L16 [get_ports {swt[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swt[1]}]
set_property PACKAGE_PIN M13 [get_ports {swt[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swt[2]}]
set_property PACKAGE_PIN R15 [get_ports {swt[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swt[3]}]
set_property PACKAGE_PIN R17 [get_ports {swt[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swt[4]}]
set_property PACKAGE_PIN T18 [get_ports {swt[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swt[5]}]
set_property PACKAGE_PIN U18 [get_ports {swt[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swt[6]}]
set_property PACKAGE_PIN R13 [get_ports {swt[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swt[7]}]

set_property PACKAGE_PIN H17 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN K15 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property PACKAGE_PIN J13 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property PACKAGE_PIN N14 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property PACKAGE_PIN R18 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property PACKAGE_PIN V17 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property PACKAGE_PIN U17 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property PACKAGE_PIN U16 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]

set_property MARK_DEBUG true [get_nets {counter_reg[0]}]
set_property MARK_DEBUG true [get_nets {counter_reg[1]}]
set_property MARK_DEBUG true [get_nets {counter_reg[2]}]
set_property MARK_DEBUG true [get_nets {counter_reg[9]}]
set_property MARK_DEBUG true [get_nets {counter_reg[18]}]
set_property MARK_DEBUG true [get_nets {counter_reg[21]}]
set_property MARK_DEBUG true [get_nets {counter_reg[22]}]
set_property MARK_DEBUG true [get_nets {counter_reg[3]}]
set_property MARK_DEBUG true [get_nets {counter_reg[5]}]
set_property MARK_DEBUG true [get_nets {counter_reg[7]}]
set_property MARK_DEBUG true [get_nets {counter_reg[14]}]
set_property MARK_DEBUG true [get_nets {counter_reg[15]}]
set_property MARK_DEBUG true [get_nets {counter_reg[20]}]
set_property MARK_DEBUG true [get_nets {counter_reg[4]}]
set_property MARK_DEBUG true [get_nets {counter_reg[12]}]
set_property MARK_DEBUG true [get_nets {counter_reg[13]}]
set_property MARK_DEBUG true [get_nets {counter_reg[17]}]
set_property MARK_DEBUG true [get_nets {counter_reg[19]}]
set_property MARK_DEBUG true [get_nets {counter_reg[24]}]
set_property MARK_DEBUG true [get_nets {counter_reg[6]}]
set_property MARK_DEBUG true [get_nets {counter_reg[8]}]
set_property MARK_DEBUG true [get_nets {counter_reg[10]}]
set_property MARK_DEBUG true [get_nets {counter_reg[11]}]
set_property MARK_DEBUG true [get_nets {counter_reg[16]}]
set_property MARK_DEBUG true [get_nets {counter_reg[23]}]
set_property MARK_DEBUG true [get_nets {counter_reg[25]}]
set_property MARK_DEBUG true [get_nets {counter_reg[26]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 27 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {counter_reg[0]} {counter_reg[1]} {counter_reg[2]} {counter_reg[3]} {counter_reg[4]} {counter_reg[5]} {counter_reg[6]} {counter_reg[7]} {counter_reg[8]} {counter_reg[9]} {counter_reg[10]} {counter_reg[11]} {counter_reg[12]} {counter_reg[13]} {counter_reg[14]} {counter_reg[15]} {counter_reg[16]} {counter_reg[17]} {counter_reg[18]} {counter_reg[19]} {counter_reg[20]} {counter_reg[21]} {counter_reg[22]} {counter_reg[23]} {counter_reg[24]} {counter_reg[25]} {counter_reg[26]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {out_value[0]} {out_value[1]} {out_value[2]} {out_value[3]} {out_value[4]} {out_value[5]} {out_value[6]} {out_value[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list direct_connect]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
