webtalk_init -webtalk_dir C:\\Users\\machs\\Software\\ECE532\\tutorial_6\\tutorial_3.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2024-01-17 17:57:07" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e7aupqkaiesq88dlll5ir06gtc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "9" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2304 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.893 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1705531830514" -context "sdk\\\\bsp/1705531830514"
webtalk_add_data -client sdk -key hwid -value "1705530997577" -context "sdk\\\\bsp/1705531830514"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1705531830514"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1705531830514"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1705531830514"
webtalk_add_data -client sdk -key uid -value "1705531831400" -context "sdk\\\\application/1705531831400"
webtalk_add_data -client sdk -key hwid -value "1705530997577" -context "sdk\\\\application/1705531831400"
webtalk_add_data -client sdk -key bspid -value "1705531830514" -context "sdk\\\\application/1705531831400"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1705531831400"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1705531831400"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1705531831400"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1705531831400"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1705531831400"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1705531831400"
webtalk_add_data -client sdk -key projSize -value "84.06640625" -context "sdk\\\\application/1705531831400"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1705532227031"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1705532227031"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1705532227031"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1705532227031"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1705532227031"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1705532227031"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1705532227031"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1705532227031"
webtalk_transmit -clientid 4156258560 -regid "" -xml C:\\Users\\machs\\Software\\ECE532\\tutorial_6\\tutorial_3.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\machs\\Software\\ECE532\\tutorial_6\\tutorial_3.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\machs\\Software\\ECE532\\tutorial_6\\tutorial_3.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
